version: '3' # 파일 규격 버전

services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  db:
    container_name: mysql # 컨테이너 이름 설정
    image: mysql:latest # 사용할 이미지
    #restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes: # -v 옵션 (다렉토리 마운트 설정)
    #- /etc/timezone:/etc/timezone:ro
    #- /etc/localtime:/etc/localtime:ro
    - ./data:/var/lib/mysql
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci